[package]
name = "numpy-example"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[lib]
name = "rust_ext"
crate-type = ["cdylib"]

[dependencies]
numpy = { path = "../.." }
ndarray = "0.12"

[dependencies.pyo3]
version = "= 0.5.0"
features = ["extension-module"]
