[package]
name = "numpy-example"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[lib]
name = "rust2py"
crate-type = ["cdylib"]

[dependencies]
numpy = { path = ".." }

[dependencies.cpython]
version = "*"
features = ["extension-module"]
